import { ArchiveHeader } from "@/components/ArchiveHeader";
import { ArchiveFooter } from "@/components/ArchiveFooter";
import { ArchiveChart } from "@/components/ArchiveChart";
import { archive, integer, observedAt, percent, totals, utcDay } from "@/lib/archive";
import { countryName } from "@/lib/format";

function Section({ number, title, description, children }: { number: string; title: string; description: string; children: React.ReactNode }) {
  return <section className="archive-section archive-results-section"><div className="archive-section-kicker">{number} / RESULTS</div><div className="archive-intro-grid"><h2>{title}</h2><p>{description}</p></div>{children}</section>;
}

export function ArchiveResults() {
  return <div className="archive-shell"><ArchiveHeader active="results" /><main>
    <div className="archive-hero archive-results-hero"><div className="archive-eyebrow"><span className="archive-square" /> ANONYMOUS ROLLUP SNAPSHOT <span>02 / THE RESULTS</span></div><h1>The record,<br /><em>in numbers.</em></h1><p>Every table below comes from the anonymous rollup payload captured on {observedAt.replace("T", " ").slice(0, 16)} UTC. Leaderboards are limited by the source API; they do not contain every observed value.</p></div>
    <div className="archive-results-nav"><a href="#daily">Daily series</a><a href="#geography">Geography</a><a href="#credentials">Credentials</a><a href="#clients">Client banners</a><a href="#techniques">Techniques</a></div>
    <Section number="01" title="Daily activity" description="Lifetime daily counts, preserved after the 30-day raw-event purge. The first and last days are partial days."><div id="daily"><ArchiveChart /><div className="archive-chart-axis"><span>{utcDay(archive.daily[0].bucketStart)}</span><span>LOGIN ATTEMPTS BY UTC DAY</span><span>{utcDay(archive.daily.at(-1)!.bucketStart)}</span></div><details className="archive-details"><summary>View all {archive.daily.length} daily counts</summary><div className="archive-table-wrap"><table><thead><tr><th>Date (UTC)</th><th className="archive-numeric">Login attempts</th></tr></thead><tbody>{archive.daily.map((row) => <tr key={row.bucketStart}><td>{utcDay(row.bucketStart)}</td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div></details></div></Section>
    <Section number="02" title="Source geography" description="Country is inferred from the source address at ingest using a local GeoIP database. It describes network location, not operator nationality or physical location."><div id="geography" className="archive-table-wrap"><table><thead><tr><th>Country</th><th className="archive-numeric">Attempts</th><th className="archive-numeric">Share</th></tr></thead><tbody>{archive.countries.map((row) => <tr key={row.key}><td>{countryName(row.key)}</td><td className="archive-numeric">{integer(row.count)}</td><td className="archive-numeric">{percent(row.count, totals.totalLoginAttempts)}</td></tr>)}</tbody></table></div><p className="archive-caption">GeoIP data: <a href="https://db-ip.com">DB-IP Lite</a>, CC BY 4.0, queried locally at ingest. Network ASNs are counted across all event types; their totals use a different denominator and should not be compared directly with the login-attempt country table.</p><details className="archive-details"><summary>View top source networks</summary><div className="archive-table-wrap"><table><thead><tr><th>ASN</th><th>Organization</th><th className="archive-numeric">Events</th></tr></thead><tbody>{archive.asns.map((row) => <tr key={row.asn}><td>AS{row.asn}</td><td>{row.org ?? "Unknown"}</td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div></details></Section>
    <Section number="03" title="Credential attempts" description="Top 20 username/password pairs from login-attempt events. The visible backslash-x-zero sequences are literal characters in the recorded strings, so we preserve them without silently interpreting them as control bytes."><div id="credentials" className="archive-table-wrap"><table><thead><tr><th>Username</th><th>Password</th><th className="archive-numeric">Attempts</th></tr></thead><tbody>{archive.credentials.map((row, i) => <tr key={`${row.username}-${row.password}-${i}`}><td><code>{row.username || "(empty)"}</code></td><td><code>{row.password || "(empty)"}</code></td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div><div className="archive-twin-tables"><div><h3>Top usernames</h3><div className="archive-table-wrap"><table><thead><tr><th>Username</th><th className="archive-numeric">Attempts</th></tr></thead><tbody>{archive.usernames.map((row) => <tr key={row.key}><td><code>{row.key || "(empty)"}</code></td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div></div><div><h3>Top passwords</h3><div className="archive-table-wrap"><table><thead><tr><th>Password</th><th className="archive-numeric">Attempts</th></tr></thead><tbody>{archive.passwords.map((row) => <tr key={row.key}><td><code>{row.key || "(empty)"}</code></td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div></div></div></Section>
    <Section number="04" title="Client banners" description="The most common self-reported SSH client version strings. A banner can be spoofed and does not identify a unique tool, bot, or person."><div id="clients" className="archive-table-wrap"><table><thead><tr><th>Client banner</th><th className="archive-numeric">Events</th></tr></thead><tbody>{archive.clients.map((row) => <tr key={row.key}><td><code>{row.key}</code></td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div></Section>
    <Section number="05" title="Observed techniques" description="Event-level classifications using MITRE ATT&CK labels. One interaction can yield several classified events. Counts are not unique incidents or confirmed compromises."><div id="techniques" className="archive-table-wrap"><table><thead><tr><th>Technique</th><th>Tactic</th><th className="archive-numeric">Events</th></tr></thead><tbody>{archive.attck.map((row) => <tr key={row.techniqueId}><td><a href={`https://attack.mitre.org/techniques/${row.techniqueId.replace(".", "/")}/`}>{row.techniqueId}</a> {row.technique}</td><td>{row.tactic}</td><td className="archive-numeric">{integer(row.count)}</td></tr>)}</tbody></table></div></Section>
    <section className="archive-section archive-data-note"><h2>Reading this archive</h2><p>Lifetime login attempts: <strong>{integer(totals.totalLoginAttempts)}</strong>. Distinct pseudonymized sources: <strong>{integer(totals.uniqueSources)}</strong>. Successful decoy logins: <strong>{integer(totals.successfulLogins)}</strong>. Sessions: <strong>{integer(totals.sessions)}</strong>. Fake-shell commands: <strong>{integer(totals.commandsEntered)}</strong>.</p><p>The last-24-hour counters and 48-hour hourly series are deliberately omitted because they become misleading after collection ends. The underlying JSON snapshot is <a href="/archive/rollups.json">available for download</a>.</p></section>
  </main><ArchiveFooter /></div>;
}
